FROM openjdk:8-jre
COPY ./target/twitterpuller-0.1.jar /usr/src/twitterpuller/
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.5.1/wait /wait
RUN chmod +x /wait
CMD /wait && java -jar /usr/src/twitterpuller/twitterpuller-0.1.jar