FROM openjdk:8-jre
COPY ./target/resource-filter-0.0.1-SNAPSHOT.jar /usr/src/resource-filter/
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.5.1/wait /wait
RUN chmod +x /wait
CMD /wait && java -jar /usr/src/resource-filter/resource-filter-0.0.1-SNAPSHOT.jar