FROM openjdk:8-jre
COPY ./target/mention-storer-0.0.1-SNAPSHOT.jar /usr/src/mention-storer/
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.5.1/wait /wait
RUN chmod +x /wait
CMD /wait && java -jar /usr/src/mention-storer/mention-storer-0.0.1-SNAPSHOT.jar