apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - env:
            - name: WAIT_HOSTS
              value: postgres-service:5432
          image: maxleopold/api
          name: api
          ports:
            - containerPort: 8081
          imagePullPolicy: Always
          workingDir: /API
      hostname: api
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: api-service-outside
spec:
  selector:
    app: api
  ports:
    - port: 8081
      targetPort: 8081
  type: LoadBalancer
