apiVersion: v1
kind: Pod
metadata:
  labels:
    app: create-collection
  name: create-collection
spec:
  containers:
    - env:
        - name: WAIT_HOSTS
          value: solr-service:8983
        - name: WAIT_HOSTS_TIMEOUT
          value: "600"
      image: maxleopold/create-collection
      name: create-collection
      imagePullPolicy: Always
  hostname: create-collection
  restartPolicy: Never
