apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resource-filter
  name: resource-filter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: resource-filter
    spec:
      containers:
      - env:
        - name: WAIT_HOSTS
          value: kafka1-service:9092
        image: maxleopold/resource-filter
        name: resource-filter
        imagePullPolicy: Always
      hostname: resource-filter
      restartPolicy: Always
  selector:
    matchLabels:
      app: resource-filter
