FROM openjdk:8-jre
COPY ./target/API-0.1.jar /usr/src/API/
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.5.1/wait /wait
RUN chmod +x /wait
CMD /wait && java -jar /usr/src/API/API-0.1.jar